version: "3.8"

services:
  client:
    image: client
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: docker/client/Dockerfile
      target: base
    environment:
      SERVER: ws://0.0.0.0:5000/
    command: npm start

  server:
    image: server
    ports:
      - 5000:5000
    depends_on:
      - client
    build:
      context: .
      dockerfile: docker/server/Dockerfile
      target: base
    command: npm run dev
